services:
    marttiphpbb.pruneinactiveusers.listener:
        class: marttiphpbb\pruneinactiveusers\event\listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }

    marttiphpbb.pruneinactiveusers.cron.task.pruneinactiveusers:
        class: marttiphpbb\pruneinactiveusers\cron\prune
        arguments:
            - '@config'
            - '@marttiphpbb.pruneinactiveusers.manager'
        calls:
            - [set_name, [cron.task.marttiphpbb_pruneinactiveusers]]
        tags:
            - { name: cron.task }

    marttiphpbb.pruneinactiveusers.manager:
        class: marttiphpbb\pruneinactiveusers\service\manager
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@log'
            - '%tables.users%'
            - '%core.root_path%'
